# Generated by Django 3.2 on 2023-01-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('origin', models.CharField(max_length=254)),
                ('year', models.CharField(max_length=20)),
                ('condition', models.CharField(choices=[('uncirculated', 'Uncirculated'), ('fine', 'Fine'), ('good', 'Good'), ('fair', 'Fair')], default=None, max_length=20)),
                ('era', models.CharField(choices=[('ancient', 'Ancient'), ('medium', 'Medium'), ('modern', 'Modern')], default=None, max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coins.metal')),
            ],
            options={
                'verbose_name_plural': 'Coins',
            },
        ),
    ]
